engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
ratings:
  paths:
  - "**.js"
  - "**.module"
exclude_paths:
- node_modules/
- coverage/
- test/
- config/
- mocks/
- docs/
- api-docs/
- code-docs/
- "**/lang/"
- "**/lib/"
ecmaFeatures:
  modules: true
  jsx: true
env:
  amd: true
  browser: true
  es6: true
  jquery: true
  node: true
